/**
 * API Route: /api/generateImage
 * Generates 4 image variants using Imagen-4 and stores in Supabase Storage
 */

import { NextRequest, NextResponse } from 'next/server'
import { generateImages } from '@/lib/vertex-ai'
import { buildCompletPrompt, buildPromptWithTextRendering, TemplateType } from '@/lib/prompt-engineering'
import { createClient } from '@supabase/supabase-js'
import { v4 as uuidv4 } from 'uuid'

// Initialize Supabase client for storage (lazy initialization)
function getSupabaseClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!url || !key) {
    throw new Error('Supabase configuration missing')
  }

  return createClient(url, key)
}

interface GenerateImageRequest {
  prompt: string
  template: TemplateType
  primaryColor?: string
  secondaryColor?: string
  accentColor?: string
  userId?: string
  useAIText?: boolean
  aiTextContent?: string
}

interface GeneratedImage {
  id: string
  url: string
  base64?: string
  storagePath: string
  createdAt: string
}

interface GenerateImageResponse {
  success: boolean
  images: GeneratedImage[]
  prompt: string
  error?: string
}

export async function POST(request: NextRequest): Promise<NextResponse<GenerateImageResponse>> {
  try {
    const body: GenerateImageRequest = await request.json()

    const { prompt: userPrompt, template, primaryColor, secondaryColor, accentColor, userId, useAIText, aiTextContent } = body

    if (!userPrompt || !userPrompt.trim()) {
      return NextResponse.json(
        {
          success: false,
          images: [],
          prompt: '',
          error: 'Prompt is required',
        },
        { status: 400 }
      )
    }

    if (!template) {
      return NextResponse.json(
        {
          success: false,
          images: [],
          prompt: '',
          error: 'Template is required',
        },
        { status: 400 }
      )
    }

    console.log('🧠 Building prompt for Imagen-4...')
    console.log('🎨 AI Text Effects enabled:', useAIText)

    // Build the complete prompt with brand context
    let completePrompt: string
    
    if (useAIText && aiTextContent) {
      // Text baking mode: render text in the image
      completePrompt = buildPromptWithTextRendering(
        userPrompt.trim(),
        aiTextContent.trim(),
        true,
        template
      )
      console.log('🎨 Using AI Text Rendering mode')
    } else {
      // Normal mode: just the image
      completePrompt = buildCompletPrompt({
        subject: userPrompt.trim(),
        template,
        primaryColor,
        secondaryColor,
        accentColor,
      })
    }

    console.log('📝 Final Imagen prompt:', completePrompt)
    console.log('🎨 Template:', template)

    // Generate images using Imagen-4
    console.log('🚀 Calling Imagen-4 API...')
    let base64Images: string[] = []

    try {
      base64Images = await generateImages({
        prompt: completePrompt,
        numberOfImages: 4,
        sampleCount: 4,
      })
    } catch (error: any) {
      console.error('🔴 Imagen-4 API error:', error)
      
      // Extract error message safely
      let errorMessage = 'Unknown error'
      if (error?.message) {
        errorMessage = error.message
      } else if (typeof error === 'string') {
        errorMessage = error
      }
      
      console.error('🔴 Extracted error message:', errorMessage)
      
      // Handle quota/rate limit errors specifically
      if (
        errorMessage.includes('Quota exceeded') ||
        errorMessage.includes('429') ||
        errorMessage.includes('Too many requests') ||
        errorMessage.includes('RESOURCE_EXHAUSTED')
      ) {
        const quotaErrorResponse: GenerateImageResponse = {
          success: false,
          images: [],
          prompt: completePrompt,
          error: `Quota exceeded: Please wait a moment and try again. The image generation service has rate limits.`,
        }
        console.log('📤 Returning quota error response:', quotaErrorResponse)
        return NextResponse.json(quotaErrorResponse, { status: 429 })
      }
      
      const errorResponse: GenerateImageResponse = {
        success: false,
        images: [],
        prompt: completePrompt,
        error: `Image generation failed: ${errorMessage}`,
      }
      console.log('📤 Returning error response:', errorResponse)
      return NextResponse.json(errorResponse, { status: 500 })
    }

    if (base64Images.length === 0) {
      console.error('🔴 No images generated by Imagen-4')
      return NextResponse.json(
        {
          success: false,
          images: [],
          prompt: completePrompt,
          error: 'No images generated by Imagen-4. Check your Google Cloud credentials.',
        },
        { status: 500 }
      )
    }

    console.log(`✨ Generated ${base64Images.length} images, uploading to Supabase Storage...`)

    // Store images in Supabase Storage
    const supabase = getSupabaseClient()
    const generatedImages: GeneratedImage[] = []
    const batchId = uuidv4()

    for (let i = 0; i < base64Images.length; i++) {
      try {
        const base64Data = base64Images[i]
        const imageId = uuidv4()

        // Convert base64 to buffer
        let imageBuffer: Buffer

        // Handle different base64 formats
        if (base64Data.startsWith('data:image')) {
          // Remove data URL prefix
          const base64String = base64Data.split(',')[1]
          imageBuffer = Buffer.from(base64String, 'base64')
        } else {
          // Direct base64
          imageBuffer = Buffer.from(base64Data, 'base64')
        }

        // Create storage path
        const timestamp = new Date().toISOString().split('T')[0]
        const userId_str = userId || 'anonymous'
        const storagePath = `generated-images/${userId_str}/${timestamp}/${batchId}/${imageId}.png`

        console.log(`⬆️  Uploading image ${i + 1}/4 to ${storagePath}`)

        // Upload to Supabase Storage
        const { data: uploadData, error: uploadError } = await supabase.storage
          .from('images')
          .upload(storagePath, imageBuffer, {
            contentType: 'image/png',
            upsert: false,
          })

        if (uploadError) {
          console.error(`Upload error for image ${i + 1}:`, uploadError)
          throw uploadError
        }

        // Get public URL
        const {
          data: { publicUrl },
        } = supabase.storage.from('images').getPublicUrl(storagePath)

        generatedImages.push({
          id: imageId,
          url: publicUrl,
          base64: base64Data, // Also return base64 for immediate display
          storagePath,
          createdAt: new Date().toISOString(),
        })

        console.log(`✅ Image ${i + 1}/4 uploaded: ${publicUrl}`)
      } catch (error) {
        console.error(`Failed to upload image ${i + 1}:`, error)
        // Continue with other images even if one fails
      }
    }

    if (generatedImages.length === 0) {
      return NextResponse.json(
        {
          success: false,
          images: [],
          prompt: completePrompt,
          error: 'Failed to upload any images to storage',
        },
        { status: 500 }
      )
    }

    console.log(`🎉 Successfully generated and stored ${generatedImages.length} images`)

    return NextResponse.json({
      success: true,
      images: generatedImages,
      prompt: completePrompt,
    })
  } catch (error: any) {
    console.error('❌ Error in /api/generateImage:', error)

    return NextResponse.json(
      {
        success: false,
        images: [],
        prompt: '',
        error: error?.message || 'Failed to generate images',
      },
      { status: 500 }
    )
  }
}
